const fs = require('fs');

const CSS_VARS = `
:root {
  --sky-dawn:    #FFD6E0;
  --sky-day:     #C8E6FF;
  --sky-dusk:    #FFCBA4;
  --sky-night:   #1A1A3E;
  --sky-night-dark: #0D0420;
  --sky-night-light: #2D1B4E;
  --sky-sunset1: #FFCBA4;
  --sky-sunset2: #FF8C6B;
  --sky-sunset3: #D4607A;
  --ground:      #A8D5A2;
  --ground-dark: #7AB87A;
  --path:        #F0E0C8;
  --water:       #B0D8F0;
  --skin:        #FFD5B8;
  --hair:        #3D2314;
  --outfit-rose: #E8A0B0;
  --outfit-gold: #D4A843;
  --dialogue-bg: rgba(20, 10, 15, 0.88);
  --dialogue-border: #D4A843;
  --choice-bg:   #3A1A24;
  --choice-hover:#C0607A;
  --text-main:   #FFF8F5;
  --text-name:   #F5E0A0;
  --text-accent: #E8A0B0;
  --font-pixel:  'Press Start 2P', monospace;
  --font-story:  'VT323', monospace;
}
`;

const spritePalette = {
  '.': 'transparent',
  'k': '#000000',
  'w': '#FFFFFF',
  's': 'var(--skin)',
  'h': 'var(--hair)',
  'r': 'var(--outfit-rose)',
  'g': 'var(--outfit-gold)',
  'p': '#FFB6C1',
  'b': '#4A90E2',
  'd': '#2C3E50',
  'c': '#9B59B6',
  'y': '#F1C40F',
  'P': '#FF69B4',
};

function generateSpriteCSS(className, asciiArt, scale = 3) {
  const lines = asciiArt.split('\n');
  const shadows = [];
  
  for (let y = 0; y < lines.length; y++) {
    const line = lines[y];
    for (let x = 0; x < line.length; x++) {
      const char = line[x];
      const color = spritePalette[char];
      if (color && color !== 'transparent') {
        shadows.push((x * scale) + 'px ' + (y * scale) + 'px ' + color);
      }
    }
  }
  
  if (shadows.length === 0) return '';
  return '\n.' + className + ' {\n  width: ' + scale + 'px;\n  height: ' + scale + 'px;\n  box-shadow: ' + shadows.join(',\n    ') + ';\n}\n';
}

const sprites = {
  'vedu_happy': [
".......hhhh.......",
"......hhhhhh......",
".....hssssssh.....",
".....hpssssph.....",
".....hhsssshh.....",
"......hhhhhh......",
".......kkkk.......",
"......rrrrrr......",
".....rrrrrrrr.....",
"....grrrrrrrrg....",
"....rr..rr..rr....",
"....rr..rr..rr....",
"........ss........",
"........ss........",
"........ss........",
".......rrrr......."].join('\n'),

  'vedu_surprised': [
".......hhhh.......",
"......hhhhhh......",
".....hs.ss.sh.....",
".....hpssssph.....",
".....hs.kk.sh.....",
"......hhhhhh......",
".......kkkk.......",
"......rrrrrr......",
".....rrrrrrrr.....",
"....grrrrrrrrg....",
"........rr........",
"........rr........",
"........ss........",
"........ss........",
"........ss........",
".......rrrr......."].join('\n'),

  'vedu_thinking': [
".......hhhh.......",
"......hhhhhh......",
".....hs.kk.sh.....",
".....hpssssph.....",
".....hs.kk.sh.....",
"......hhhhhh......",
".......kkkk.......",
"......rrrrrr......",
".....rssssrrrr....",
"....gs....rrrg....",
"........rr........",
"........rr........",
"........ss........",
".......rrrr.......",
".......rrrr......."].join('\n'),

  'vedu_sleeping': [
"                  ",
"                  ",
"                  ",
"      hhhhhh      ",
"     hssssssh     ",
"     hp ss ph     ",
"     hssssssh     ",
"     rrrrrrrr     ",
"    grrrrrrrrg    ",
"    rr  rr  rr    ",
"        ss        ",
"        ss        "].join('\n'),

  'vedu_laughing': [
"       hhhh       ",
"      hhhhhh      ",
"     hpksssph     ",
"     hpssssph     ",
"     hskkkksh     ",
"      hhhhhh      ",
"       kkkk       ",
"      rrrrrr      ",
"     rrrrrrrr     ",
"    grrrrrrrrg    ",
"        rr        ",
"        rr        ",
"        ss        ",
"       rrrr       "].join('\n'),

  'navi_smile': [
"       hhhh       ",
"      hhhhhh      ",
"     hs ss sh     ",
"     hssssssh     ",
"     hhsssshh     ",
"      hhhhhh      ",
"       ssss       ",
"      bbbbbb      ",
"     bbbbbbbb     ",
"    bbbbbbbbbb    ",
"    bb  bb  bb    ",
"    bb  bb  bb    ",
"        dd        ",
"        dd        ",
"        dd        ",
"        dd        ",
"       kkkk       "].join('\n'),

  'navi_proud': [
"       hhhh       ",
"      hhhhhh      ",
"     hs ss sh     ",
"     hssssssh     ",
"     hskkkksh     ",
"      hhhhhh      ",
"       ssss       ",
"      bbbbbb      ",
"     bbbbbbbb     ",
"    ssssbbssss    ",
"        bb        ",
"        bb        ",
"        dd        ",
"        dd        ",
"        dd        ",
"        dd        ",
"       kkkk       "].join('\n'),

  'navi_wave': [
"       hhhh       ",
"  s   hhhhhh      ",
"  s  hs ss sh     ",
"  s  hssssssh     ",
"  ssshhsssshh     ",
"      hhhhhh      ",
"       ssss       ",
"      bbbbbb      ",
"     bbbbbbbb     ",
"    bb  bb        ",
"    bb  bb        ",
"        dd        ",
"        dd        ",
"        dd        ",
"        dd        ",
"       kkkk       "].join('\n'),

  'bunny_idle': [
"   ww    ww   ",
"   ww    ww   ",
"  wPw    wPw  ",
"  wPw    wPw  ",
"   ww    ww   ",
"   wwwwwwww   ",
"  w        w  ",
"  wk      kw  ",
"  w        w  ",
"  w   P    w  ",
"   w      w   ",
"   wwwwwwww   ",
"    ww  ww    "].join('\n'),

  'star_cat': [
"  c        c  ",
"  cc      cc  ",
" cccc    cccc ",
" cccccccccccc ",
" cyyccccccyyc ",
" cccccccccccc ",
" cccccyyccccc ",
"  cccccccccccc",
"   cccccccc  c",
"    cccccc   c",
"     cccc    c"].join('\n'),

  'shopkeeper': [
"       wwww       ",
"      wwwwww      ",
"     w ss sw      ",
"     ssssssss     ",
"     ssssssss     ",
"       ssss       ",
"      yyyyyy      ",
"     yyyyyyyy     ",
"    yy      yy    ",
"    yy      yy    ",
"        dd        ",
"        dd        ",
"        dd        ",
"       kkkk       "].join('\n'),

  'kpop_singer': [
"       hhhh       ",
"      hhhhhh      ",
"     h ss sh      ",
"     ssssssss     ",
"     ssssssss     ",
"       ssss       ",
"      wwyyww      ",
"     wyyyyyyw     ",
"    w        w    ",
"    w        w    ",
"        dd        ",
"        dd        ",
"        dd        ",
"       kkkk       ",
"       kkkk       ",
"       kkkk       "].join('\n'),
  
  'flower_1': [
"  yy  ",
" PyyP ",
"  PP  ",
"   g  ",
"   g  "].join('\n'),

  'flower_2': [
"  ww  ",
" ywwy ",
"  ww  ",
"   g  ",
"   g  "].join('\n'),

  'cake': [
"   y   ",
"   w   ",
"  www  ",
" wwwww ",
"PPwwwPP",
"PPPPPPP",
"yPPPPPy",
"ryyyyyr"].join('\n'),
};

let allSpritesCSS = '';
for (const [name, art] of Object.entries(sprites)) {
  allSpritesCSS += generateSpriteCSS('sprite-' + name, art, 3);
}

const logicStr = fs.readFileSync('logic.js', 'utf8');

const htmlArr = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1.0">',
"  <title>A Day in Vedu's World 🌸</title>",
'  <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323:wght@400&display=swap" rel="stylesheet">',
'  <style>',
CSS_VARS,
'* { box-sizing: border-box; }',
'body {',
'  margin: 0; padding: 0;',
'  background-color: #000;',
'  overflow: hidden;',
'  font-family: var(--font-story);',
'  color: var(--text-main);',
'}',
'',
'#root {',
'  width: 100vw; height: 100vh;',
'  display: flex;',
'  align-items: center;',
'  justify-content: center;',
'}',
'',
'#game-container {',
'  width: 480px; height: 270px;',
'  position: absolute;',
'  left: 50%; top: 50%;',
'  margin-left: -240px; margin-top: -135px;',
'  transform-origin: center;',
'  image-rendering: -moz-crisp-edges;',
'  image-rendering: -webkit-optimize-contrast;',
'  image-rendering: crisp-edges;',
'  image-rendering: pixelated;',
'  overflow: hidden;',
'}',
'',
'#bg-layer {',
'  position: absolute;',
'  width: 100%; height: 100%;',
'  transition: opacity 1s, background 1s;',
'}',
'',
'.bg-bedroom {',
'  background: linear-gradient(180deg, var(--sky-dawn) 0%, #FFECF0 40%, #FFF0F5 40%, #FFF0F5 75%, #F0D8C0 75%);',
'}',
'.bg-bedroom::after {',
'  content: ""; position: absolute;',
'  top: 10%; right: 10%; width: 60px; height: 80px;',
'  border: 4px solid #fff; background: rgba(255,255,255,0.2);',
'}',
'',
'.bg-town_street {',
'  background: linear-gradient(180deg, var(--sky-day) 0%, #E8F4FF 60%, var(--ground-dark) 60%, var(--ground) 65%);',
'}',
'.bg-town_street::after {',
'  content: ""; position: absolute;',
'  bottom: 0; left: 50%; transform: translateX(-50%);',
'  width: 120px; height: 100px; background: var(--path);',
'}',
'',
'.bg-music_room {',
'  background: linear-gradient(180deg, #5c3a21 0%, #3a1c0d 100%);',
'  border-left: 20px solid #2a1105;',
'  border-right: 20px solid #2a1105;',
'}',
'',
'.bg-garden {',
'  background: linear-gradient(180deg, var(--sky-sunset1) 0%, var(--sky-sunset2) 40%, var(--sky-sunset3) 60%, var(--ground-dark) 60%, var(--ground) 65%);',
'}',
'',
'.bg-dream_world {',
'  background: linear-gradient(180deg, var(--sky-night-dark) 0%, var(--sky-night) 50%, var(--sky-night-light) 100%);',
'}',
'',
'.bg-ending {',
'  background: linear-gradient(180deg, #090211 0%, #170A2D 100%);',
'}',
allSpritesCSS,
'.character-slot {',
'  position: absolute;',
'  bottom: 40px;',
'  transition: opacity 0.5s, transform 0.5s;',
'  image-rendering: inherit;',
'  opacity: 0;',
'}',
'',
'#char-left { left: 80px; }',
'#char-center { left: 220px; }',
'#char-right { left: 360px; }',
'',
'#ui-layer {',
'  position: absolute;',
'  width: 100%; height: 100%;',
'  pointer-events: none;',
'  z-index: 100;',
'}',
'',
'#dialogue-box {',
'  position: absolute;',
'  bottom: 0; width: 100%; height: 75px;',
'  background: var(--dialogue-bg);',
'  border-top: 2px solid var(--dialogue-border);',
'  padding: 10px 15px;',
'  display: none;',
'  pointer-events: auto;',
'  cursor: pointer;',
'}',
'',
'#speaker-name {',
'  font-family: var(--font-pixel);',
'  font-size: 8px;',
'  color: var(--text-name);',
'  margin-bottom: 6px;',
'  text-transform: uppercase;',
'}',
'',
'#dialogue-text {',
'  font-size: 22px;',
'  line-height: 1.2;',
'}',
'',
'#continue-indicator {',
'  position: absolute;',
'  bottom: 8px; right: 10px;',
'  font-family: var(--font-pixel); font-size: 8px;',
'  animation: blink 1s infinite;',
'  display: none;',
'}',
'',
'@keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }',
'',
'#choices-container {',
'  position: absolute;',
'  bottom: 85px; width: 100%;',
'  display: flex; flex-direction: column; align-items: center;',
'  gap: 6px;',
'  pointer-events: auto;',
'}',
'',
'.choice-btn {',
'  background: var(--choice-bg);',
'  border: 2px solid var(--outfit-rose);',
'  color: var(--text-main);',
'  font-family: var(--font-story);',
'  font-size: 20px;',
'  padding: 4px 16px;',
'  border-radius: 12px;',
'  cursor: pointer;',
'  width: 80%;',
'  text-align: left;',
'  transition: all 0.15s ease;',
'}',
'.choice-btn:hover {',
'  background: var(--choice-hover);',
'  border-color: var(--outfit-gold);',
'  transform: scale(1.02);',
'}',
'',
'#transition-overlay {',
'  position: absolute;',
'  top:0; left:0; width:100%; height:100%;',
'  background: transparent;',
'  pointer-events: none;',
'  z-index: 200;',
'  display: flex; flex-wrap: wrap;',
'}',
'.transition-pixel {',
'  width: 60px; height: 54px;',
'  background: #000;',
'  transform: scale(0);',
'}',
'@keyframes pixelIn {',
'  to { transform: scale(1.05); }',
'}',
'@keyframes pixelOut {',
'  from { transform: scale(1.05); }',
'  to { transform: scale(0); }',
'}',
'',
'#title-screen {',
'  position: absolute; width:100%; height:100%;',
'  background: #000;',
'  display: flex; flex-direction: column; align-items: center; justify-content: center;',
'  z-index: 50;',
'  pointer-events: auto;',
'}',
'.title-box {',
'  border: 2px solid var(--outfit-gold);',
'  padding: 20px;',
'  text-align: center;',
'  background: rgba(0,0,0,0.8);',
'}',
'.title-text {',
'  font-family: var(--font-pixel);',
'  font-size: 10px;',
'  color: var(--outfit-gold);',
'  margin-bottom: 20px;',
'  line-height: 1.5;',
'}',
'.title-btn {',
'  font-family: var(--font-pixel); font-size: 8px;',
'  background: transparent; color: #fff;',
'  border: none; cursor: pointer;',
'  margin: 5px; opacity: 0.8;',
'}',
'.title-btn:hover { color: var(--outfit-gold); opacity: 1; }',
'',
'#chapter-title {',
'  position: absolute; top:0; left:0; width:100%; height:100%;',
'  background: rgba(0,0,0,0.9);',
'  color: var(--outfit-gold);',
'  font-family: var(--font-pixel); font-size: 12px;',
'  display: flex; align-items: center; justify-content: center;',
'  z-index: 40; opacity: 0; pointer-events: none;',
'  transition: opacity 0.5s;',
'}',
'',
'#hud {',
'  position: absolute;',
'  top: 5px; left: 5px; right: 5px;',
'  display: flex; justify-content: space-between;',
'  font-family: var(--font-pixel); font-size: 6px;',
'  color: #fff; opacity: 0.5;',
'}',
'',
'canvas#particle-canvas {',
'  position: absolute; top:0; left:0; pointer-events:none; z-index: 50;',
'}',
'',
'@keyframes bunnyIdle {',
'  0%, 100% { transform: translateY(0px); }',
'  50% { transform: translateY(-4px); }',
'}',
'.anim-bounce { animation: bunnyIdle 0.8s steps(2) infinite; }',
'',
'.anim-glow { filter: drop-shadow(0 0 4px var(--outfit-gold)) drop-shadow(0 0 8px var(--outfit-gold)); }',
'',
'.anim-fadein { animation: fadeIn 2s forwards; }',
'@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }',
'',
'.ending-text {',
'  position: absolute;',
'  bottom: 40px; width:100%; text-align:center;',
'  pointer-events: none;',
'}',
'.ending-line { margin: 5px 0; }',
'  </style>',
'</head>',
'<body>',
'  <div id="root">',
'    <div id="game-container">',
'      <div id="bg-layer" class="bg-bedroom"></div>',
'      ',
'      <!-- Characters -->',
'      <div id="char-left" class="character-slot"></div>',
'      <div id="char-center" class="character-slot"></div>',
'      <div id="char-right" class="character-slot"></div>',
'      ',
'      <canvas id="particle-canvas" width="480" height="270"></canvas>',
'',
'      <div id="ui-layer">',
'        <div id="hud">',
'          <span id="bgm-label">♪ none</span>',
'          <span id="mute-btn" style="cursor:pointer">♪ ON</span>',
'        </div>',
'        ',
'        <div id="chapter-title">ACT 1 - THE MORNING</div>',
'',
'        <div id="choices-container"></div>',
'        <div id="dialogue-box">',
'          <div id="speaker-name"></div>',
'          <div id="dialogue-text"></div>',
'          <div id="continue-indicator">▼</div>',
'        </div>',
'      </div>',
'',
'      <div id="title-screen">',
'        <div class="title-box">',
"          <div class=\"title-text\">✦ A DAY IN VEDU'S WORLD ✦</div>",
'          <button class="title-btn" id="btn-start">[ ▶ START ]</button><br>',
'          <button class="title-btn" id="btn-about">[ ◆ ABOUT ]</button>',
'        </div>',
'      </div>',
'',
'      <div id="transition-overlay"></div>',
'    </div>',
'  </div>',
'<script>',
logicStr,
'</script>',
'</body>',
'</html>'
];

var outHTML = htmlArr.join('\n');
fs.writeFileSync('index.html', outHTML);
